name: dnd_example_simple_sortable
version: 0.0.0
author: Marco Jakob <majakob@gmx.ch>
description: 'Dart Drag and Drop Example'
homepage: http://code.makery.ch/library/dart-drag-and-drop/
dependencies:
  browser: any
  dnd:
    path: ../../
